name: Build Docker Container Image and Push to ACR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: SampleWeb
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: dockerhemanth.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t dockerhemanth.azurecr.io/app:${{ github.sha }}
        docker push dockerhemanth.azurecr.io/hello-world:${{ github.sha }}
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'CloudQuickLabsWebApp'
        images: 'cloudquicklabsacr.azurecr.io/myapp:${{ github.sha }}'
    
    - name: Azure logout
      run: |
        az logout
        
